### ISSUE TITLE
How can I analysis the core dump file created by minicoredumper?

### ISSUE THREAD

**Issue by LeeOnion** [diamon/minicoredumper#11]
I find **Efficient and Practical Capturing ofCrash Data on Embedded Systems** PPT said that the disadvantages of coredump is debugging tools required for analysis.
So when I use minicoredumper, how can I analysis the core dump file created by minicoredumper?

**Comment by jogness** [comment]
Hi,

Core dump files created by the minicoredumper can be read using gdb (or any other tool that is used for reading core dumps). They are valid core dump files.

The slides you are referring to talk about some disadvantages of the normal Linux core dumping facility. And in this case, it is talking about a disadvantage of core dumps in general. To work around this disadvantage, the minicoredumper **also** supports other methods of getting debug information. In particular, the slides mention the use of libminicoredumper to create custom-format files for easy viewing of important data.

**Comment by LeeOnion** [comment]
OK, Thank you for your reply~

**Comment by LeeOnion** [comment]
Hi jogness,
There are two questions after trying minicoredumper:
1. minicoredumper.cfg.json has a key word which name **comm**,  I know what is exe, but I cant undetstand comm.
2. I have used mcd_dump_data_register_text api, but I am not sure about mcd_dump_data_unregister. Do I need call mcd_dump_data_unregister when I finish my function?(just like malloc and free?) If I don't call mcd_dump_data_unregister , what will happend?

**Comment by LeeOnion** [comment]
By the way, how can I build minicoredumper by aarch64-linux-gnu-gcc? I try to read config file and makefile, but I am not sure about it.

**Comment by LeeOnion** [comment]
Now I register info by mcd_dump_data_register_text api, and then I try to use minicoredumper_trigger to dump. I can find a dir but there is no file in dir.My minicoredumper version is 2.0.1.

**Comment by jogness** [comment]
> 1. Now I register info by mcd_dump_data_register_text api, and then I try to use minicoredumper_trigger to dump. I can find a dir but there is no file in dir.My minicoredumper version is 2.0.1.

Do you have minicoredumper_regd running? If you are using the provided start script to start the minicoredumper, you can activate minicoredumper_regd by setting:

    MINICOREDUMPER_REGD_START=1

in `/etc/default/minicoredumper`

> 2. I find the config json supports dump_robust_mutex_list, but I can't find thers is any cmds in gdb to fetch it. How can I get robust_mutex info in coredump file.

The address is shown in the minicoredumper log output. For example:

    minicoredumper: dump: robust mutex head: 24 bytes @ 0x7f59b1af2a20

This points to `struct robust_list_head`, which you could view in gdb with:

    (gdb) print *(struct robust_list_head *)0x7f59b1af2a20
