### ISSUE TITLE
Question about Version2.0.6

### ISSUE THREAD

**Issue by LeeOnion** [diamon/minicoredumper#12]
I try to compile V2.0.6 with aarch64-linux-gnu, but I cant create coredump file. And then I remove the minicoredump and minicoredump_regd, and just use  the minicoredump and minicoredump_regd of V2.0.1(for ubuntu deb), and then I can create coredump file.
![img_v3_0262_691ae118-18a2-4edd-861e-f64d81616cag](https://github.com/diamon/minicoredumper/assets/35868504/f1ee9231-10d3-490a-bfef-34b758634448)
![img_v3_0262_4604678d-6bb7-45e2-9a02-aa95a021df4g](https://github.com/diamon/minicoredumper/assets/35868504/cd2f2e71-f0ca-4702-8e33-165c42253350)

**Comment by jogness** [comment]
Please look in /var/log/syslog for error messages. Or use `journalctl | grep minicoredumper'

**Comment by LeeOnion** [comment]
The following is the log of 2.0.6 and 2.0.1(only the difference of usr/sbin/minicoredumper):
minicoredumper[362] is failed for unable to parse config file.
`struct config *init_config(const char *cfg_file)
{
	struct json_object *o;
	struct config *cfg;

	cfg = calloc(1, sizeof(*cfg));
	if (!cfg)
		return NULL;
	o = **json_object_from_file**(cfg_file);
	if (!o) {
		fatal("unable to parse config file: %s", strerror(errno));
		free(cfg);
		return NULL;
	}

	if (read_base_config(o, cfg) < 0) {
		fatal("unable to read base config");
		free(cfg);
		cfg = NULL;
	}

	json_object_put(o);

	return cfg;
}`
![image](https://github.com/diamon/minicoredumper/assets/35868504/9820b853-c9fb-408f-ade2-8f14cd33aad1)

**Comment by jogness** [comment]
The error message is quite clear: No such file or directory.

When you manually built 2.0.6 you specify where the configuration files are. Did you use --sysconfdir=/etc with configure?
