### ISSUE TITLE
Convenience way to dump all global/static memory?

### ISSUE THREAD

**Issue by Haoqian-He** [diamon/minicoredumper#14]
Hi, Minicoredumper experts,

According to the FAQ, 
> Using the tool nm on the library or executable containing the symbol, it is possible to see the name of the symbol as used by the linker. This name can be specified as one of the buffers of a recept file.

I know how to dump a global/static variable. However, is there any quick way to dump all global/static variables for gdb debugging?

Thanks!

**Comment by jogness** [comment]
The global/static variables will be stored in the data segment. It should be enough to list the executable path in the maps to dump. For example, for a program /usr/bin/myprog it would look like this in your recept file:

```
{
    ...
    "maps": {
        "dump_by_name": [
            "/usr/bin/myprog",
            "[vdso]"
        ]
    },
    ...
}
```
It is important that the string matches what is seen in /proc/PID/maps

Note that this will only dump the data segment for the executable. Libraries may have their own global/static variables.

**Comment by Haoqian-He** [comment]
Thank u John, i got it.
But we cannot know the global/static variable which in .bss segment yet, does minicoredumper support dump .bss memory?

**Comment by jogness** [comment]
Well, that will give you part of the .bss memory. The rest will be in anonymous memory. If you do not mind dumping a bit more than you actually need, you could dump this as well by specifying the empty string "":

```
{
    ...
    "maps": {
        "dump_by_name": [
            "/usr/bin/myprog",
            "",
            "[vdso]"
        ]
    },
    ...
}
```

**Comment by Haoqian-He** [comment]
Thanks John, It does work and i find the corresponding code.
``` C
int simple_match(const char *pattern, const char *string)
{
	if (*pattern == 0 && *string == 0) {
		/* reached the end of both strings => match! */
		return 0;
	}
        ...
}
```

BTW, i'm confused about whether all the binary file that wants to generate core files should be written in the maps field for the **.data** segment memory. This  seems a bit troublesome.

emm... of course i have a tmp solution, using core pattern parameter %E (Pathname of executable, with slashes ('/') replaced by exclamation marks ('!') (since Linux 3.0).), which can be applied to all process and could dump the **.data** memory in the core.

**Comment by jogness** [comment]
> BTW, i'm confused about whether all the binary file that wants to generate core files should be written in the maps field for the **.data** segment memory. This seems a bit troublesome.

You can use different recept files for different executables. The minicoredumper.cfg.json specifies the matching rules.

But yes, if you want a generic solution that will grab the full .data segments for all possible (known and unknown) executables, then it will be difficult. I suppose you could just use a wildcard match for all pathnames:

```
{
    ...
    "maps": {
        "dump_by_name": [
            "/*",
            "",
            "[vdso]"
        ]
    },
    ...
}
```
