### ISSUE TITLE
Is it possible to dump thread local storage?

### ISSUE THREAD

**Issue by zhangtianze1997** [diamon/minicoredumper#16]
Hello,

I failed to check the thread local variables in coredump generated by minicoredumper. GDB reported an error:
```
(gdb) p my_thread
Cannot find thread-local storage for Thread 0x7f9941e31700 (LWP 54659), executable file /root/test:
generic error
```
Does the minicoredumper support dumping TLS?
Thx.

**Comment by jogness** [comment]
No, it does not. You could use libminicoredumper to register the variables manually.
