### ISSUE TITLE
The read will in an infinite loop

### ISSUE THREAD

**Issue by dongyang626** [diamon/minicoredumper#8]
Hi guys.

In the below situation, the read will in an infinite loop:

If the PID 123 triggered the core dump and Minicoredumper started to read the /proc/123/mem (dump_compressed_tar-->copy_data-->read_file_fd).
At this time, if the OOM is triggered, then the PID 123 is killed by SIGKILL.
The read will return zero. 

But in the read_file_fd, the code doesn't check the zero condition.   When the "r" is 0,  the "len" will never to 0,  then into an infinite loop. 
```C
static ssize_t read_file_fd(int fd, char *dst, int len)
{
	size_t size = 0;
	int r;

	do {
		r = read(fd, dst + size, len);

		if (r == -1) {
			info("Couldn't read file fd=%d; error %s", fd,
			     strerror(errno));
			return r;
		}

		if (r > 0) {

			size += r;
			len -= r;
		}
	} while (len > 0);

	return size;
}
```

I'm also checking whether the read return zero is reasonable.  Maybe it should return -1 (Input/output error)?

Anyway, I think we need to add a check for "read return 0". 

Here is our patch, please check it, thanks :)
[0001-minicoredumper-add-return-check-for-read-funcfion.patch](https://github.com/diamon/minicoredumper/files/11019031/0001-minicoredumper-add-return-check-for-read-funcfion.patch)

Best Regards,
Dongyang

**Comment by jogness** [comment]
Thanks for reporting and fixing this. I have applied the fix as https://github.com/diamon/minicoredumper/commit/5bc4beb4c605470f4566d1f7563b9a6b5c45b3af in master.
